### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tschaffter**
#### Changelog

- Run `ncu -u`
- Keep RxJS slightly behind to satisfy dependencies
- Disable building storybook until a patch is found by the storybook author, see [storybook ticket for this issue](https://github.com/storybookjs/storybook/issues/15227)

### CODE REVIEW

**Comment by tschaffter** [comment]
This command below works locally for me: `ng build sage-angular-demo --configuration production --baseHref="https://sage-bionetworks.github.io/sage-angular/pr-34/demo/"`

**Comment by tschaffter** [comment]
The command `build:storybook` fails:

```
...
info => Using angular-cli webpack config
info => Using default Webpack4 setup
ERR! WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.module.rules[9] has an unknown property 'mimetype'. These properties are valid:
ERR!    object { compiler?, enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, realResource?, resolve?, resource?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }
ERR!    -> A rule
ERR!     at webpack (/home/tschaffter/dev2/sage-bionetworks/rocc/rocc-app/sage-angular/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/webpack.js:31:9)
ERR!     at Object.build (/home/tschaffter/dev2/sage-bionetworks/rocc/rocc-app/sage-angular/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:179:18)
ERR!     at async Promise.all (index 1)
ERR!     at async buildStaticStandalone (/home/tschaffter/dev2/sage-bionetworks/rocc/rocc-app/sage-angular/node_modules/@storybook/core-server/dist/cjs/build-static.js:141:28)
ERR!     at async Object.buildStatic (/home/tschaffter/dev2/sage-bionetworks/rocc/rocc-app/sage-angular/node_modules/@storybook/core-server/dist/cjs/build-static.js:161:5)
ERR!  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.module.rules[9] has an unknown property 'mimetype'. These properties are valid:
ERR!    object { compiler?, enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, realResource?, resolve?, resource?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }
ERR!    -> A rule
ERR!     at webpack (/home/tschaffter/dev2/sage-bionetworks/rocc/rocc-app/sage-angular/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/webpack.js:31:9)
ERR!     at Object.build (/home/tschaffter/dev2/sage-bionetworks/rocc/rocc-app/sage-angular/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:179:18)
ERR!     at async Promise.all (index 1)
ERR!     at async buildStaticStandalone (/home/tschaffter/dev2/sage-bionetworks/rocc/rocc-app/sage-angular/node_modules/@storybook/core-server/dist/cjs/build-static.js:141:28)
ERR!     at async Object.buildStatic (/home/tschaffter/dev2/sage-bionetworks/rocc/rocc-app/sage-angular/node_modules/@storybook/core-server/dist/cjs/build-static.js:161:5)
```

**Comment by tschaffter** [comment]
Followed Storybook instructions for [upgrading to Angular 12](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-12-upgrade).

**Comment by tschaffter** [comment]
Starting the storybook locally works but building it gets stuck.

```
92% sealing asset processing TerserPlugininfo => Manager built (26 s)
info => Preview built (38 s)
WARN System.import() is deprecated and will be removed soon. Use import() instead.
WARN For more info visit https://webpack.js.org/guides/code-splitting/
WARN System.import() is deprecated and will be removed soon. Use import() instead.
WARN For more info visit https://webpack.js.org/guides/code-splitting/
WARN asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
WARN This can impact web performance.
WARN Assets:
WARN   main.f9fa072c.iframe.bundle.js (587 KiB)
WARN   716.a82bccd1.iframe.bundle.js (4.34 MiB)
WARN entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
WARN Entrypoints:
WARN   main (4.92 MiB)
WARN       runtime~main.f5400cfc.iframe.bundle.js
WARN       716.a82bccd1.iframe.bundle.js
WARN       main.f9fa072c.iframe.bundle.js
WARN
info => Output directory: /home/tschaffter/dev2/sage-bionetworks/rocc/rocc-app/sage-angular/storybook-static
```

- Tried installing `terser-webpack-plugin` as suggested [here](https://github.com/storybookjs/storybook/issues/13893#issuecomment-815629482).

**Comment by tschaffter** [comment]
Same issue as https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#gistcomment-3792216

**Comment by tschaffter** [comment]
I tried again with Storybook 6.2.9. The build is successful and here are the last line. So it's possible that the build with 6.3.2 is "successful" (files are created) but the command does not return.

```
92% chunk asset optimization TerserPlugininfo => Manager built (25 s)
info => Preview built (31 s)
WARN asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
WARN This can impact web performance.
WARN Assets:
WARN   main.e75f0e7d.iframe.bundle.js (592 KiB)
WARN   vendors~main.180972ff.iframe.bundle.js (4.19 MiB)
WARN entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
WARN Entrypoints:
WARN   main (4.77 MiB)
WARN       runtime~main.032c0cce.iframe.bundle.js
WARN       vendors~main.180972ff.iframe.bundle.js
WARN       main.e75f0e7d.iframe.bundle.js
WARN
info => Output directory: /home/tschaffter/dev2/sage-bionetworks/rocc/rocc-app/sage-angular/storybook-static
```

**Comment by tschaffter** [comment]
Found the official issue: https://github.com/storybookjs/storybook/issues/15227

**Comment by vpchung** [comment]
Nice sleuthing, @tschaffter !

**Pull request merged**
